### ISSUE TITLE
bbox parameter should be validated

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap-API#104] opened 2017-08-15 09:06 UTC
Out of bounds coordinates in `bbox` return `Internal Server Error`.

https://api.opensensemap.org/boxes/data?phenomenon=Temperatur&bbox=-999,-1,1,1

**Comment by ubergesundheit** [comment] 2017-08-15 09:08
Duplicate of #46 
Will be live once https://github.com/sensebox/openSenseMap-API/commit/f8e4b2364c553f7686bf82755dc9563ad67b4de0 makes its way into `master`

**Closed by ubergesundheit** 2017-08-15 09:08 UTC
